name: Release BEAR AI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'BEAR AI v__VERSION__'
          releaseBody: |
            🐻 BEAR AI Local LLM Assistant

            Download and run the installer for your platform:
            - Windows: BEAR-AI_x64-setup.exe

            Features:
            ✅ 100% Local - No internet required
            ✅ PII Protection built-in
            ✅ GPU/CPU auto-detection
            ✅ Hugging Face model support

            See installation guide for details.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe